### ISSUE TITLE
Recursive transclusion error in transclude widget  on media annotation when GSD5 plug in is enabled

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/mediaplayer#10]
https://scribe.tiddlyhost.com/#Tweet-khaledzeid-acute%20eosinophilic%20pneumonia.mp4

![image](https://user-images.githubusercontent.com/67494083/221004189-e7b9b423-5e32-44cf-b495-a2b0ee41ef67.png)

This occurs when the GSD5 plug in is enabled. Any fixes for this ?

**Comment by buggyj** [comment]
there are two widgets both called 'toggle' one in my plugin the other within GSD5. The easiest solution is for me to update the mediaplayer plugin

**Comment by buggyj** [comment]
new version here:

https://mediaplayerava.tiddlyhost.com/#%24%3A%2Fplugins%2Fbj%2Fmediaplayer
