### ISSUE TITLE
Remove slices and extras of the annotation tiddlers from the Recent section

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/mediaplayer#12]
In streams plug in, there is an option to remove child nodes from the Recent section using this code - https://saqimtiaz.github.io/streams/#FAQs%2FHow%20can%20I%20show%20only%20the%20stream%20root%20tiddlers%20in%20the%20timeline%3F

Can something like that be done for the slices and extras of the annotation tiddlers since it will clutter the Recent section.

**Comment by buggyj** [comment]
that's a good idea

`<$macrocall $name="timeline" format={{$:/language/RecentChanges/DateFormat}} subfilter='!regexp[slice]'/>`

**Comment by arunnbabu81** [comment]
> 

Thank you. Thats works.

How to combine `subfilter="get-stream-root[]"` and `subfilter='!regexp[slice]'`

**Comment by buggyj** [comment]
have you tried `subfilter='!regexp[slice]get-stream-root[]'`

**Comment by arunnbabu81** [comment]
> 

This works.
