### ISSUE TITLE
Show caption instead of title for the slice tiddlers

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/mediaplayer#14]
It would be nice if the caption field of the slice tiddlers are shown in the annotation template instead of their title. This is because the title doesn't convey any meaning. But if caption field is used we can add some meaningful caption for each slices. Something similar was present in the old mediaplayer plug in if I remember correctly.

![Screenshot_20230226_005952_Chrome](https://user-images.githubusercontent.com/67494083/221376474-71dab5fe-f773-4310-8c5a-54d765cb8f9a.jpg)

**Comment by buggyj** [comment]
On the demo the summary fields are show - if you upload your tw to tiddlyhost I will take a look

**Comment by arunnbabu81** [comment]
[Demo](https://scribe-backup.tiddlyhost.com/#OnePlus%2011%20Review%3A%20They're%20Back%3F?!)

**Comment by buggyj** [comment]
they do not have summary fields -

**Comment by buggyj** [comment]
you need to create some captions for them

**Comment by arunnbabu81** [comment]
> they do not have summary fields -

Now I understood. I thought the first edit-text widget next to the start time button was for showing the start time. Now only I understood that it's for the summary field
