### ISSUE TITLE
Is it possible to integrate youtube annotation plug in with mediaplayer

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/mediaplayer#3]
Is it possible to integrate [youtube annotation plug in ](http://youtube.tiddlyspot.com/#Start) by tobibeer with the mediaplayer so that the  annotations and timestamps comes below the mediaplayer.

Or is possible to add annotation option to the mediaplayer plug in similar to tobibeers plug in

**Comment by buggyj** [comment]
I am seeing a problem with the youtube js library that is stopping me implementing yt-end time, so until I find away around this problem it is not possible.

**Comment by arunnbabu81** [comment]
Please try to make this work when you get enough time. It would be a nice addition. 

Tobibeers plug in was working fine in my wiki. Did you check the [javascript macros used in that plug in](http://youtube.tiddlyspot.com/#YoutubePlugin:Start%20YoutubePlugin%20%24%3A%2Fplugins%2Ftobibeer%2Fyoutube%2Fmacros%2Fyt.js)

**Comment by arunnbabu81** [comment]
> I am seeing a problem with the youtube js library that is stopping me implementing yt-end time, so until I find away around this problem it is not possible.

WIll the annotation feature be added to mediaplayer in the near future or shall i continue using the youtube annotation plug in by tobibeer for the time being.

**Comment by buggyj** [comment]
I can no longer reproduce the error.

you can can add `yt-start` and `yt-end` to the media tiddlers, and see if you find a bug.

**Comment by arunnbabu81** [comment]
> I can no longer reproduce the error.
> 
> you can can add `yt-start` and `yt-end` to the media tiddlers, and see if you find a bug.

How can i add yt-start and yt-end from the mediaplayer UI?
I will have to open the video tiddler seperately (outside of the mediaplayer UI)for doing that ?
i was thinking of a UI where the annotation tiddlers are created and organised below the mediaplayer  and above the individual playlist controller. 


Another thing i noticed is that the media annotation tiddlers position shift from below the video itself to above the tiddler title field after installation of mediaplayer plug in. Any idea what is causing it?

This is images shows the UI before installation of mediaplayer plug in 
![Screenshot_20220213-184154_Tiddloid](https://user-images.githubusercontent.com/67494083/153754799-c07c61a7-be14-4c11-93cf-149b9ac906d3.jpg)


This is the image of same youtube video tiddler after the installation of mediaplayer plug in. The annotation tiddlers are seen overlapping the tiddler toolbar

![Screenshot_20220213-184013_Tiddloid](https://user-images.githubusercontent.com/67494083/153754790-65d10464-dcc1-44ed-bf58-6b794594a8ef.jpg)

**Comment by buggyj** [comment]
Try disabling the plugin and see if the TW reverts to how it looked before.

The media player does not have a fixed UI, it is designed to be modified or changed completely. 
What is seen in the plugin is the UI that I use for playing music. I have a large number of mp3s that I organise into playLists using tags and drag and drop.
If you want to emulate what is in yt annotations plugin then another template would be required.

**Comment by arunnbabu81** [comment]
> Try disabling the plugin and see if the TW reverts to how it looked before.

I will investigate and report back

> 
> The media player does not have a fixed UI, it is designed to be modified or changed completely. What is seen in the plugin is the UI that I use for playing music. I have a large number of mp3s that I organise into playLists using tags and drag and drop. If you want to emulate what is in yt annotations plugin then another template would be required.

Can you guide me how to make such a template

**Comment by buggyj** [comment]
I will make a simple template and put it on tiddlyspot

**Comment by arunnbabu81** [comment]
> > Try disabling the plugin and see if the TW reverts to how it looked before.
> 
> I will investigate and report back
> 

It was not due to mediaplayer, but due to stylesheet modification done for the tiddler tag fields

**Comment by arunnbabu81** [comment]
> I will make a simple template and put it on tiddlyspot

Any updates regarding the template

**Comment by buggyj** [comment]
It will be ready soon

**Comment by arunnbabu81** [comment]
> It will be ready soon

I have seen that you have made some new commits to the mediaplayer repo. Is it ready for testing ?

**Comment by buggyj** [comment]
I will put a new version on tiddlyspot tomorrow that you can have a look at.

**Comment by buggyj** [comment]
@arunnbabu81 I have put up a new version

There is a new tiddlyclip command to start an annotation

**Comment by arunnbabu81** [comment]
> @arunnbabu81 I have put up a new version
> 
> There is a new tiddlyclip command to start an annotation

Thank you so much. I just tried it now. Its awesome to see the media player and annotations together.
I have one doubt. I saw the `Chill summer vlog` has annotations. But rest of the videos doesn't have annotations. How to start annotating those videos which doesn't have annotations.


I added new videos using the `ytnotes `rule and annotated them, but those videos are not opening in the mediaplayer tidddler.

Can you add an option to add some text to those annotated tiddlers.

**Comment by buggyj** [comment]
you drag and drop them  onto the top part of the mediaplayer tiddler


![image](https://user-images.githubusercontent.com/2855795/155402409-9ef9a6f2-d3cb-4714-a672-b3246ec651d5.png)

**Comment by buggyj** [comment]
There are two youtube commands - one to add simple video and the other to added annotated  videos. You cannot add annotations to simple video clips.

**Comment by arunnbabu81** [comment]
> you drag and drop them onto the top part of the mediaplayer tiddler
> 
> ![image](https://user-images.githubusercontent.com/2855795/155402409-9ef9a6f2-d3cb-4714-a672-b3246ec651d5.png)

Now i understood.
So we will have to drag and drop the video tiddler into the `list of playlist` at the top for annotating within the mediaplayer. That means if the video is part of a playlist, then I will have to drag and drop it again to the `list of playlist` at the top for annotating.

Can there a way to start annotating from the bottom` individual playlist` if the video is part of a playlist instead of drag and drop the video again into the top `list of playlist`.

**Comment by buggyj** [comment]
The `$:/bj/templates/playListYTNotations` template can be modified to display addition text.

here is one possibility:

add this macro to the top of the template:

`\define extra(tid) <$transclude tiddler="$tid$/extra" mode="block"/>`

like so:
![image](https://user-images.githubusercontent.com/2855795/155408035-04394032-06c8-4d4c-bc68-ea2d25e46a45.png)

and this to the bottom of the template:

`<$macrocall $name="extra" tid={{{[<synctid>get[text]]}}}/>`

like so:

![image](https://user-images.githubusercontent.com/2855795/155408193-9e0a97c5-de05-416e-a8b0-811714faf4e9.png)


you can then create extra content to be displayed when the annotation is playing, but creating a new tiddler with the same name as the individual 'slice' of the annotation follow by `/text` like so:

![image](https://user-images.githubusercontent.com/2855795/155408755-296c649c-3091-4865-a783-56c002ecb823.png)

**Comment by buggyj** [comment]
You can see the name of an anotation by hovering the mouse over it - firefox will show the link at the bottom of the screen:

![image](https://user-images.githubusercontent.com/2855795/155409616-e10e1e76-4799-4ad9-b7ca-a60bde179e73.png)

**Comment by buggyj** [comment]
here is a version with the automatic creation
[templates_playListYTNotations.json.zip](https://github.com/buggyj/mediaplayer/files/8127909/templates_playListYTNotations.json.zip)

**Comment by arunnbabu81** [comment]
> here is a version with the automatic creation [templates_playListYTNotations.json.zip](https://github.com/buggyj/mediaplayer/files/8127909/templates_playListYTNotations.json.zip)

Thank you for explaining in detail. I will give feedback after using for a few days

**Comment by arunnbabu81** [comment]
Can you update the plug-in to 2.0.4 in mediaplayer tiddlyspot

**Comment by buggyj** [comment]
ok, the tiddlyclip tid Ytdets is also updated

**Comment by arunnbabu81** [comment]
These are my few suggestions

1. The box next to the `yt-end` button shall be used to enter the title of the `slice` tiddler (which is by default `parent tiddler name/slice`) and it shall be edited manuallly. Currently the text typed in this box is being saved in the `summary `field of the slice tiddler.

2. Can the `extra` tiddler be avoided and the text typed in the newly added `text box` below the timestamps be saved in the body of the `slice` tiddler itself.

3. Can an  `edit ` and `save` button be added to right side of the `text box ` so that we get a visual feedback
     -   when we want to edit the text (`edit ` button )
     -   when we want be sure that typed text is being saved (`save` button )

4. Another button near the `slice`  tiddlers is desirable so that we can open that `slice `tiddler in the story river

**Comment by buggyj** [comment]
>> **Answers to:**

These are my few suggestions

1. The box next to the `yt-end` button shall be used to enter the title of the `slice` tiddler (which is by default `parent tiddler name/slice`) and it shall be edited manuallly. Currently the text typed in this box is being saved in the `summary `field of the slice tiddler.

>> **I expect that the summary of a slice will often be 'main argument' or 'rebuttal' etc - as tiddlers must have unique titles this would cause problems, i.e. there can only one tiddler called 'rebuttal'.**

2. Can the `extra` tiddler be avoided and the text typed in the newly added `text box` below the timestamps be saved in the body of the `slice` tiddler itself.
>> **Each slice is a media tiddler and by convention use the _cannonical_uri format for external sources. This means the text(body) field cannot be used in these tiddlers**
3. Can an  `edit ` and `save` button be added to right side of the `text box ` so that we get a visual feedback
     -   when we want to edit the text (`edit ` button )
     -   when we want be sure that typed text is being saved (`save` button )

>> **Editing a tiddler in this manner within another tiddler is difficult to do  in vanilla tiddlywiki (may be you could ask about this in the forum)** 

4. Another button near the `slice`  tiddlers is desirable so that we can open that `slice `tiddler in the story river
>> **this is possible**

**Comment by buggyj** [comment]
Answer to 4.

to the end of tiddler $:/bj/templates/isEditYTNextra add

`{{||$:/core/ui/Buttons/edit}}`

**Comment by arunnbabu81** [comment]
> Answer to 4.
> 
> to the end of tiddler $:/bj/templates/isEditYTNextra add
> 
> `{{||$:/core/ui/Buttons/edit}}`

Should  i add `{{||$:/core/ui/Buttons/edit}}` to  `$:/bj/templates/isEditYTNextra`  or `$:/bj/templates/isEditYTN`.

![image](https://user-images.githubusercontent.com/67494083/155771147-30e7661f-e046-4d30-8481-f685b56ed8da.png)

The button is seen when i add `{{||$:/core/ui/Buttons/edit}}` to  `$:/bj/templates/isEditYTN` only

**Comment by arunnbabu81** [comment]
![image](https://user-images.githubusercontent.com/67494083/155771639-c9f79aea-2ce5-4a5a-bc1c-1574076876b6.png)


Why does the  youtube video doesn't play in the slice tiddler

**Comment by buggyj** [comment]
if you edit the tiddler `Chill Summer........|Daloka` you will see the template that it is using - you may need to update to include the `exta`.

youtube video does not play in the slice tiddler because tiddlywiki does not support youtube videos directly. I have not added support for playing youtube videos in the 'story' - it is not something I would use.

**Comment by buggyj** [comment]
You can try this:

[parsers_utubeparser.js.json.zip](https://github.com/buggyj/mediaplayer/files/8144207/parsers_utubeparser.js.json.zip)

**Comment by arunnbabu81** [comment]
> if you edit the tiddler `Chill Summer........|Daloka` you will see the template that it is using - you may need to update to include the `exta`.
> 
I didn't understand it fully

**Comment by arunnbabu81** [comment]
You should share the mediaplayer in the talk tiddlywiki forum so that other also can use it.

**Comment by buggyj** [comment]
Actually the template $:/bj/templates/playListYTNotationsExtra is calling $:/bj/templates/isEditYTN this is an error I will have to fix.

The mediaplayer is still not stable, I may still have to make some changes - maybe changing the web address that is used in the _canonical_uri from the actual web address of youtube to what youtube uses in the iframe.
